local appconfig = {}

appconfig.CARD_HOVER_ANIMATION_SPEED = 10
appconfig.CARD_ENTRANCE_SPEED = 6
appconfig.CARD_ENTRANCE_STAGGER = 0.1
appconfig.CARD_ENTRANCE_MAX_DT = 1 / 60

appconfig.DAMAGE_JITTER_DURATION = 0.28
appconfig.DAMAGE_JITTER_MAGNITUDE = 7
appconfig.DESTRUCTION_DURATION = 0.6

appconfig.KIT_RETURN_FLASH_DURATION = 0.1
appconfig.KIT_RETURN_EXPAND_DURATION = 0.14
appconfig.KIT_RETURN_FLY_DURATION = 0.28
appconfig.KIT_RETURN_TOTAL_DURATION = appconfig.KIT_RETURN_FLASH_DURATION
    + appconfig.KIT_RETURN_EXPAND_DURATION
    + appconfig.KIT_RETURN_FLY_DURATION

appconfig.PILOT_VEHICLE_ANIMATION_DURATION = 0.58
appconfig.HUNTER_AUTO_PLAY_ANIMATION_DURATION = 0.46

appconfig.MULLIGAN_PROMPT_FADE_DURATION = 0.16
appconfig.MULLIGAN_REPLACEMENT_ANIMATION_DURATION = 0.28
appconfig.MULLIGAN_REPLACEMENT_SLIDE_OFFSET = 96

appconfig.WORLD_TO_MISSION_TRANSITION_DURATION = 0.82
appconfig.WORLD_TO_MISSION_BURN_BAND_HEIGHT = 92
appconfig.WORLD_TO_MISSION_BURN_STRIP_COUNT = 44

return appconfig
